version: "3.3"

services:
 nginx_web:
  image: nginx:1.16
  container_name: nginx_web
  ports:
  - 10083:80
  - 50000:50000
  volumes:
  - /task/4/index.html:/usr/share/nginx/html/index.html
  env_file:
  - /task/4/nginx_env
  logging:
   driver: journald