version: "3"

services:
 web:
  image: nginx:alpine
  environment:
   - TZ=Europe/Minsk
  ports:
   - 80:80
   - 443:443
  tmpfs:
   - /run
   - /tmp
   - /var/cache/nginx

volumes:
 runv:
 tmpv:
 nginxv:
